var ping={Lib:{},namespace:function(a,b){for(var c=a.split("."),d=window[c[0]]=window[c[0]]||{},e=1;e<c.length;e++)d=d[c[e]]=d[c[e]]||{};return d},w:function(a,b){b.call(a.prototype)},Exception:function(a,b){this.message=a;this.scope=b}};ping.Exception.prototype.toString=function(){return"ping.Exception( "+this.message+", ... );"};ping.CTX=null;ping.Lib=ping.Lib||{};ping.Lib.CnvMan=function(){this.refs={}};ping.Lib.CnvMan.prototype._set=function(a,b){this.refs[a]=b};ping.Lib.CnvMan.prototype.get=function(a){"undefined"==typeof this.refs[a]&&this._set(a,ping.Lib.$C(a));return this.refs[a]};ping.Lib.CnvMan.prototype.set=function(a,b){"undefined"==typeof this.refs[a]&&this._set(a,b);return this.refs[a]};ping.Lib.CnvMan.prototype.exists=function(a){return"undefined"!=typeof this.refs[a]};ping.cMngr=new ping.Lib.CnvMan;
ping.$C=function(a){if(ping.cMngr.exists(a))return ping.cMngr.get(a);var b=document.getElementById(a).getContext("2d");return ping.cMngr.set(a,b)};CanvasRenderingContext2D.prototype.render=function(a){this.beginPath();a.call(this);this.closePath();return this};CanvasRenderingContext2D.prototype.rayGen=function(a,b,c,d){b=b*Math.PI/180;c=a*Math.cos(b)+c;a=a*Math.sin(b)+d;return[c,a]};
CanvasRenderingContext2D.prototype.elipGen=function(a,b,c,d,e){e=1.8;b=b*Math.PI/180;c=a*Math.cos(b)*e+c;a=0.5*a*Math.sin(b)+d;return[c,a]};CanvasRenderingContext2D.prototype.line=function(a,b){this.moveTo(b.x,b.y);this.lineTo(a.x,a.y)};CanvasRenderingContext2D.prototype.drawLine=CanvasRenderingContext2D.prototype.line;CanvasRenderingContext2D.prototype.circle=function(a,b,c){return this.arc(a,b,c,0,2*Math.PI,!0)};
CanvasRenderingContext2D.prototype.drawCircle=function(a,b,c){this.beginPath();this.circle(a,b,c);this.closePath()};CanvasRenderingContext2D.prototype.pixel=function(a,b){this.save();this.moveTo(a[0],a[1]);this.fillStyle=b;this.fillRect(a[0],a[1],1,1);this.restore()};CanvasRenderingContext2D.prototype.putPixel=function(a,b,c){var d=1==arguments.length?a:[a,b];this.pixel(d,c||"white")};
CanvasRenderingContext2D.prototype.floodFill=function(a){this.save();this.fillStyle=a;this.fillRect(0,0,this.canvas.clientWidth,this.canvas.clientHeight);this.restore()};CanvasRenderingContext2D.prototype.clearAll=function(a){this.clearRect(0,0,this.canvas.clientWidth,this.canvas.clientHeight)};CanvasRenderingContext2D.prototype.maxHeight=function(){return this.canvas.clientHeight};CanvasRenderingContext2D.prototype.maxWidth=function(){return this.canvas.clientWidth};
ping.Lib.CanvasRenderingContext2D=CanvasRenderingContext2D;ping.Lib=ping.Lib||{};ping.Lib.intersects=ping.Lib.intersects||{};
ping.Lib.intersects.box=function(a,b){return a.x>=b.x&&a.x<=b.x+b.sx&&a.y>=b.y&&a.y<=b.y+b.sy||a.x+a.sx>=b.x&&a.x+a.sx<=b.x+b.sx&&a.y>=b.y&&a.y<=b.y+b.sy||a.x+a.sx>=b.x&&a.x+a.sx<=b.x+b.sx&&a.y+a.sy>=b.y&&a.y+a.sy<=b.y+b.sy||a.x>=b.x&&a.x<=b.x+b.sx&&a.y+a.sy>=b.y&&a.y+a.sy<=b.y+b.sy||b.x>=a.x&&b.x<=a.x+a.sx&&b.y>=a.y&&b.y<=a.y+a.sy||b.x+b.sx>=a.x&&b.x+b.sx<=a.x+a.sx&&b.y>=a.y&&b.y<=a.y+a.sy||b.x+b.sx>=a.x&&b.x+b.sx<=a.x+a.sx&&b.y+b.sy>=a.y&&b.y+b.sy<=a.y+a.sy||b.x>=a.x&&b.x<=a.x+a.sx&&b.y+b.sy>=a.y&&
b.y+b.sy<=a.y+a.sy?!0:!1};ping.Lib.MainLoop=function(){var a=this;a.constantList=[];a.runQueue=[];var b=null;a.logicLoop=function(){$.each(a.constantList,function(b,d){try{d()}catch(e){console.debug(e),a.stop()}});0<a.runQueue.length&&runQueue.shift()()};a.start=function(){b=setInterval(a.logicLoop,10)};a.stop=function(){clearInterval(b)}};ping.Lib=ping.Lib||{};ping.Shapes=ping.Shapes||{};ping.Lib.pointDistance=function(a,b,c,d){a=Math.pow(a-c,2);b=Math.pow(b-d,2);return Math.sqrt(a+b)};ping.Lib.Point=function(a,b){this.x=a;this.y=b};ping.Lib.Point.prototype.dist=function(a){return ping.Lib.pointDistance(this.x,a.x,this.y,a.y)};ping.Lib.Point.prototype.slope=function(a){return(this.y-a.y)/(this.x-a.x)};ping.Lib.Line=function(a,b){this.begin=a;this.end=b};ping.Lib.Line.prototype.COINCIDENT=2;ping.Lib.Line.prototype.PARALLEL=4;
ping.Lib.Line.prototype.NO_INTERSECT=8;ping.Lib.Line.prototype.INTERSECT=16;ping.Lib.Line.prototype.slope=function(a){return this.begin.slope(this.end)};ping.Lib.Line.prototype.dist=function(){return this.begin.dist(this.end)};
ping.Lib.Line.prototype.intersect=function(a){var b=(a.end.y-a.begin.y)*(this.end.x-this.begin.x)-(a.end.x-a.begin.x)*(this.end.y-this.begin.y),c=(a.end.x-a.begin.x)*(this.begin.y-a.begin.y)-(a.end.y-a.begin.y)*(this.begin.x-a.begin.x);a=(this.end.x-this.begin.x)*(this.begin.y-a.begin.y)-(this.end.y-this.begin.y)*(this.begin.x-a.begin.x);if(0==b)return 0==c&&0==a?[this.COINCIDENT]:[this.PARALLEL];c/=b;b=a/b;return 0<=c&&1>=c&&0<=b&&1>=b?[this.INTERSECT,this.begin.x+c*(this.end.x-this.begin.x),this.begin.y+
c*(this.end.y-this.begin.y)]:[this.NO_INTERSECT]};ping.Lib=ping.Lib||{};
ping.Lib.boxfactory=function(){var a,b;switch(arguments.length){case 3:a=new ping.Lib.Point(arguments[0],arguments[1]);b=arguments[2];break;case 2:a=arguments[0];b=arguments[1];break;default:throw new ping.Exception("ping.Lib.boxFactory expects (point, size) or (x, y, size) only");}var c=new ping.Lib.Point(a.x,a.y),d=new ping.Lib.Point(a.x+b,a.y),e=new ping.Lib.Point(a.x+b,a.y+b);a=new ping.Lib.Point(a.x,a.y+b);c=new ping.Lib.Line(c,d);e=new ping.Lib.Line(c.end,e);d=new ping.Lib.Line(e.end,a);a=new ping.Lib.Line(d.end,
c.begin);return[c,e,d,a]};function GUID(){return(new Date).getTime()+(65536*(1+Math.random())|0).toString(16).substring(1)+(65536*(1+Math.random())|0).toString(16).substring(1)+(65536*(1+Math.random())|0).toString(16).substring(1)}function Ball(a,b,c,d,e){this.id=GUID();this.x=a;this.y=b;this.sy=this.sx=c;this.dx=d;this.dy=e}Ball.prototype.bbox=function(){return{x:this.x-this.sx,y:this.y-this.sy,sx:this.sx,sy:this.sx}};Ball.prototype.step=function(){this.x+=this.dx;this.y+=this.dy};
function ballFactory(a,b){var c=Math.random()*a,d=Math.random()*b,e=20*Math.random()-10,f=20*Math.random()-10;return new Ball(c,d,60,e,f)}function RunBall(a,b){a.dx*=0.5;a.dy*=0.5;0.5>Math.abs(a.dx)&&(a.dx=0<a.dx?0.5:-0.5);0.5>Math.abs(a.dy)&&(a.dy=0<a.dy?0.5:-0.5);ping.Lib.util.inside(a.x,0,575)||(a.dx*=-1);ping.Lib.util.inside(a.y,0,375)||(a.dy*=-1);return a}
function RenderBall(a,b,c){for(var d=a.bbox(),e=b.findBox(d,e),f=b=null,k=null,l="blue",g=e.length-1;0<=g;g--)if(e[g].entities)for(var f=e[g],h=0;h<f.entities.length;h++)if(b=f.entities[h],b.id!=a.id&&(k=ping.Lib.pointDistance(a.x,a.y,b.x,b.y),ping.Lib.intersects.box(d,b.bbox())&&(c.save(),c.beginPath(),c.strokeStyle="black",c.moveTo(Math.round(a.x),Math.round(a.y)),c.lineTo(Math.round(b.x),Math.round(b.y)),c.closePath(),c.stroke(),c.restore()),16>k)){l="red";a.dx*=-1.5;a.dy*=-1.5;a.x+=5*a.dx;a.y+=
5*a.dy;b.dx*=-1.5;b.dy*=-1.5;b.x+=5*b.dx;b.y+=5*b.dy;f.entities[h]=b;break}c.save();c.fillStyle=l;c.beginPath();c.circle(a.x,a.y,10);c.closePath();c.fill();c.restore();return a}function zf(a){var b;b=3-a.toString().length;return 0<b?Array(b+(/\./.test(a)?2:1)).join("0")+a:a}
function traversal(a,b){this instanceof Quadrant&&(a=this);var c;c="<li>"+("\n "+a.name+" - "+a.depth+"["+zf(a.x)+","+zf(a.y)+"] ["+zf(a.sx)+","+zf(a.sy)+"]");var d=a.loop(traversal);0<d.length&&(d=d.join("\n"),c+="<ul>"+d+"</ul>");return c+"</li>"};ping.Lib=ping.Lib||{};ping.Lib.initInput=function(){ping.Lib.Input=function(){var a=this,b={38:"U",40:"D",37:"L",39:"R"};a.state={U:!1,D:!1,L:!1,R:!1};a.keydown=function(c){c=b[c.which];"undefined"!=c&&(a.state[c]=!0)};a.keyup=function(c){(c=b[c.which])&&(a.state[c]=!1)};$(document).keydown(a.keydown);$(document).keyup(a.keyup)}};ping.Lib.util=ping.Lib.util||{};ping.Lib.util.inside=function(a,b,c){return a>b&a<c};ping.Lib.util.insideBox=function(a,b,c){var d=c.x||c[0],e=c.y||c[1],f=c.sy||c[3];return ping.Lib.util.inside(a,d,d+(c.sx||c[2]))&&ping.Lib.util.inside(b,e,e+f)};ping.Lib.Quadrant=function(a,b,c,d,e,f){this.x=a;this.y=b;this.sx=c;this.sy=d;this.depth=e-1;this.entities=[];this.name=f||"root";this.lr=this.ur=this.ll=this.ul=null};
ping.Lib.Quadrant.prototype.ulAddIf=function(a){var b=[this.x,this.y,this.sx/2,this.sy/2];return ping.Lib.util.insideBox(a.x,a.y,b)?(null==this.ul&&(this.ul=new ping.Lib.Quadrant(b[0],b[1],b[2],b[3],this.depth-1,this.name+"->ul")),this.ul.add(a),!0):!1};
ping.Lib.Quadrant.prototype.urAddIf=function(a){var b=[this.x+this.sx/2,this.y,this.sx/2,this.sy/2];return ping.Lib.util.insideBox(a.x,a.y,b)?(null==this.ur&&(this.ur=node=new ping.Lib.Quadrant(b[0],b[1],b[2],b[3],this.depth-1,this.name+"->ur")),this.ur.add(a),!0):!1};
ping.Lib.Quadrant.prototype.llAddIf=function(a){var b=[this.x,this.y+this.sy/2,this.sx/2,this.sy/2];return ping.Lib.util.insideBox(a.x,a.y,b)?(null==this.ll&&(this.ll=new ping.Lib.Quadrant(b[0],b[1],b[2],b[3],this.depth-1,this.name+"->ur")),this.ll.add(a),!0):!1};
ping.Lib.Quadrant.prototype.lrAddIf=function(a){var b=[this.x+this.sx/2,this.y+this.sy/2,this.sx/2,this.sy/2];return ping.Lib.util.insideBox(a.x,a.y,b)?(null==this.lr&&(this.lr=new ping.Lib.Quadrant(b[0],b[1],b[2],b[3],this.depth-1,this.name+"->lr")),this.lr.add(a),!0):!1};ping.Lib.Quadrant.prototype.contains=function(a,b){return a>this.x&&a<this.x+this.sx&&b>this.y&&b<this.y+this.sy};ping.Lib.Quadrant.prototype.containsBox=function(a){return ping.Lib.intersects.box(this,a)};
ping.Lib.Quadrant.prototype.add=function(a){if(null==this.entities)return this.lrAddIf(a)||this.urAddIf(a)||this.llAddIf(a)||this.ulAddIf(a);1<=this.entities.length&&1<this.depth?(this.entities.push(a),this.divide(),this.entities=null):this.entities.push(a);return!0};ping.Lib.Quadrant.prototype.divide=function(){var a=this.entities.pop();if(a){do this.lrAddIf(a)||this.urAddIf(a)||this.llAddIf(a)||this.ulAddIf(a),this.entities.pop();while(a)}};
ping.Lib.Quadrant.prototype.render=function(a,b){a.strokeRect(this.x,this.y,this.sx,this.sy);this.ul&&this.ul.render(a,b-1);this.ur&&this.ur.render(a,b-1);this.lr&&this.lr.render(a,b-1);this.ll&&this.ll.render(a,b-1)};ping.Lib.Quadrant.prototype.loop=function(a){console.error("Deprecated, non-performent!");for(var b=[],c=["ul","ll","ur","lr"],d=0;d<c.length;d++)this[c[d]]instanceof ping.Lib.Quadrant&&b.push(a.call(this[c[d]],c[d]));return b};
ping.Lib.Quadrant.prototype.find=function(a,b){var c=[];if(this.contains(a,b)&&(c.push(this),null==this.entities)){var d=[];this.ul&&(d=d.concat(this.ul.find(a,b,c)));this.ur&&(d=d.concat(this.ur.find(a,b,c)));this.lr&&(d=d.concat(this.lr.find(a,b,c)));this.ll&&(d=d.concat(this.ll.find(a,b,c)));return c.concat(d)}return c};
ping.Lib.Quadrant.prototype.findBox=function(a){if(null==this.entities){var b=[];this.ul&&this.ul.containsBox(a)&&(b=b.concat(this.ul.findBox(a)));this.ur&&this.ur.containsBox(a)&&(b=b.concat(this.ur.findBox(a)));this.lr&&this.lr.containsBox(a)&&(b=b.concat(this.lr.findBox(a)));this.ll&&this.ll.containsBox(a)&&(b=b.concat(this.ll.findBox(a)));return b}return this.entities};ping.QuadrantFactory=function(a,b){return new ping.Lib.Quadrant(0,0,a.canvas.clientWidth,a.canvas.clientHeight,b||4)};ping.Lib.util=ping.Lib.util||{};ping.Lib.util.inside=function(a,b,c){return a>b&a<c};ping.Lib.util.insideBox=function(a,b,c){var d=c.x||c[0],e=c.y||c[1],f=c.sy||c[3];return ping.Lib.util.inside(a,d,d+(c.sx||c[2]))&&ping.Lib.util.inside(b,e,e+f)};function Quadrant(a,b,c,d,e,f){this.x=a;this.y=b;this.sx=c;this.sy=d;this.depth=e-1;this.entities=[];this.name=f||"root";this.lr=this.ur=this.ll=this.ul=null}
Quadrant.prototype.ulAddIf=function(a){var b=[this.x,this.y,this.sx/2,this.sy/2];return ping.Lib.util.insideBox(a.x,a.y,b)?(null==this.ul&&(this.ul=new Quadrant(b[0],b[1],b[2],b[3],this.depth-1,this.name+"->ul")),this.ul.add(a),!0):!1};Quadrant.prototype.urAddIf=function(a){var b=[this.x+this.sx/2,this.y,this.sx/2,this.sy/2];return ping.Lib.util.insideBox(a.x,a.y,b)?(null==this.ur&&(this.ur=node=new Quadrant(b[0],b[1],b[2],b[3],this.depth-1,this.name+"->ur")),this.ur.add(a),!0):!1};
Quadrant.prototype.llAddIf=function(a){var b=[this.x,this.y+this.sy/2,this.sx/2,this.sy/2];return ping.Lib.util.insideBox(a.x,a.y,b)?(null==this.ll&&(this.ll=new Quadrant(b[0],b[1],b[2],b[3],this.depth-1,this.name+"->ur")),this.ll.add(a),!0):!1};Quadrant.prototype.lrAddIf=function(a){var b=[this.x+this.sx/2,this.y+this.sy/2,this.sx/2,this.sy/2];return ping.Lib.util.insideBox(a.x,a.y,b)?(null==this.lr&&(this.lr=new Quadrant(b[0],b[1],b[2],b[3],this.depth-1,this.name+"->lr")),this.lr.add(a),!0):!1};
Quadrant.prototype.contains=function(a,b){return a>this.x&&a<this.x+this.sx&&b>this.y&&b<this.y+this.sy};Quadrant.prototype.containsBox=function(a){return ping.Lib.intersects.box(this,a)};Quadrant.prototype.add=function(a){null==this.entities?this.lrAddIf(a)||this.urAddIf(a)||this.llAddIf(a)||this.ulAddIf(a):1<=this.entities.length&&1<this.depth?(this.entities.push(a),this.divide(),this.entities=null):this.entities.push(a)};
Quadrant.prototype.divide=function(){for(var a=null;a=this.entities.pop();)this.lrAddIf(a)||this.urAddIf(a)||this.llAddIf(a)||this.ulAddIf(a)};Quadrant.prototype.render=function(a,b){a.strokeRect(this.x,this.y,this.sx,this.sy);this.ul&&this.ul.render(a,b-1);this.ur&&this.ur.render(a,b-1);this.lr&&this.lr.render(a,b-1);this.ll&&this.ll.render(a,b-1)};
Quadrant.prototype.loop=function(a){for(var b=[],c=["ul","ll","ur","lr"],d=0;d<c.length;d++)this[c[d]]instanceof Quadrant&&b.push(a.call(this[c[d]],c[d]));return b};Quadrant.prototype.find=function(a,b){var c=[];if(this.contains(a,b)&&(c.push(this),null==this.entities)){var d=[];this.ul&&(d=d.concat(this.ul.find(a,b,c)));this.ur&&(d=d.concat(this.ur.find(a,b,c)));this.lr&&(d=d.concat(this.lr.find(a,b,c)));this.ll&&(d=d.concat(this.ll.find(a,b,c)));return c.concat(d)}return c};
Quadrant.prototype.findBox=function(a){if(null==this.entities){var b=[];this.ul&&this.ul.containsBox(a)&&(b=b.concat(this.ul.findBox(a)));this.ur&&this.ur.containsBox(a)&&(b=b.concat(this.ur.findBox(a)));this.lr&&this.lr.containsBox(a)&&(b=b.concat(this.lr.findBox(a)));this.ll&&this.ll.containsBox(a)&&(b=b.concat(this.ll.findBox(a)));return b}return[this]};function QuadrantFactory(a,b){return new Quadrant(0,0,a.canvas.clientWidth,a.canvas.clientHeight,b||4)}(function(){console.log("Test here!")})();
